Update demo.yml

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -14,10 +14,10 @@ on:
   pull_request:
     branches: ["PART_1_and_2"]
 
-jobs:
-  buids:
-      name: Node steps
-      runs-on: ubuntu-latest
+# jobs:
+#   buids:
+#       name: Node steps
+#       runs-on: ubuntu-latest
 #       steps:
 #         - name: buils web app
 #           run : |
@@ -45,18 +45,45 @@ jobs:
 # #             client_payload: '{"sha": "test"}' 
 #         - run: |
 #             echo " ${{ github.ref_name }} "
-      steps:
-        - name: Dispatch an action and get the run ID
-          uses: codex-/return-dispatch@v1
-          id: return_dispatch
-          with:
-            token: ${{ secrets.G_ACCESS_TOKEN }} # Note this is NOT GITHUB_TOKEN but a PAT
-            ref: main # or refs/heads/target_branch
-            repo: frontend_react 
-            owner: techay-mihir-simform
-            workflow: root.yml
-            workflow_inputs: '{ "distinct_id": "testtest" }' # Optional
-            workflow_timeout_seconds: 120 # Default: 300
+#       steps:
+#         - name: Dispatch an action and get the run ID
+#           uses: codex-/return-dispatch@v1
+#           id: return_dispatch
+#           with:
+#             token: ${{ secrets.G_ACCESS_TOKEN }} # Note this is NOT GITHUB_TOKEN but a PAT
+#             ref: main # or refs/heads/target_branch
+#             repo: frontend_react 
+#             owner: techay-mihir-simform
+#             workflow: root.yml
+#             workflow_inputs: '{ "distinct_id": "testtest" }' # Optional
+#             workflow_timeout_seconds: 120 # Default: 300
 
-        - name: Use the output run ID
-          run: echo ${{steps.return_dispatch.outputs.run_id}}
+# name: Action Test
+# on:
+#   pull_request:
+#   push:
+
+jobs:
+  test:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Dispatch and return Run ID
+        id: return_dispatch
+        uses: ./
+        with:
+          token: ${{ secrets.G_ACCESS_TOKEN }}
+          ref: main
+          repo: frontend_react
+          owner: techay-mihir-simform
+          workflow: root.yml
+          workflow_inputs: '{"cake":"delicious"}'
+          workflow_timeout_seconds: 30
+      - name: Evaluate that the Run ID output has been set
+        run: |
+          if [ "${{ steps.return_dispatch.outputs.run_id }}" == "" ]; then
+            echo "Failed to return Run ID"
+            exit 1
+          fi
+      - name: Output fetched Run ID
+        run: echo ${{ steps.return_dispatch.outputs.run_id }}
